= Freelancer Application

[source,bash]

----
 ██████╗ ██╗   ██╗ █████╗ ██████╗ ██╗  ██╗██╗   ██╗███████╗                       
██╔═══██╗██║   ██║██╔══██╗██╔══██╗██║ ██╔╝██║   ██║██╔════╝                       
██║   ██║██║   ██║███████║██████╔╝█████╔╝ ██║   ██║███████╗                       
██║▄▄ ██║██║   ██║██╔══██║██╔══██╗██╔═██╗ ██║   ██║╚════██║                       
╚██████╔╝╚██████╔╝██║  ██║██║  ██║██║  ██╗╚██████╔╝███████║                       
 ╚══▀▀═╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝                       
███████╗██████╗ ███████╗███████╗██╗      █████╗ ███╗   ██╗ ██████╗███████╗██████╗ 
██╔════╝██╔══██╗██╔════╝██╔════╝██║     ██╔══██╗████╗  ██║██╔════╝██╔════╝██╔══██╗
█████╗  ██████╔╝█████╗  █████╗  ██║     ███████║██╔██╗ ██║██║     █████╗  ██████╔╝
██╔══╝  ██╔══██╗██╔══╝  ██╔══╝  ██║     ██╔══██║██║╚██╗██║██║     ██╔══╝  ██╔══██╗
██║     ██║  ██║███████╗███████╗███████╗██║  ██║██║ ╚████║╚██████╗███████╗██║  ██║
╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝╚══════╝╚═╝  ╚═╝
                                                                                  
----

Sample application developed with Quarkus with following functions:

* RESTful API
* JPA (for access database i.e. PostgreSQ and H2)
* Health Check (Liveness and Readiness)
* OpenAPI (with Swagger UI)
* Microprofile Metrics
* Unit Test with REST Assured


URI supported by application

[options=header]
|===
|URI|Method|Description
|/freelancers|GET|get all freelancers
|/freelancers/{freelancerId}|GET|get freelancer by Id
|/freelancers|POST|add new freelancer
|/freelancers/{freelancer}|PUT|update freelancer by Id
|/freelancers/{freelancer}|DELETE|delete freelancer by Id
|/metrics/application|GET|Get metrics data (with header Accept: application/json for JSON)
|/health|GET|Health check for liveness and readiness
|/health/live|GET|Livenness probe
|/health/ready|GET|Readiness probe
|/openapi|GET|Return OpenAPI document in yaml 
|/openapi?format=json|GET|Return OpenAPI document in JSON 
|/swagger-ui|GET|Swagger UI (only in Dev profile) 
|===

== Build JAR
Quarkus 1.3.1 needs maven 3.6.3+

[source,bash]
----
# Compile
mvn clean compile

# Build With Dev Profile
# Dev profile is configured with H2 database
mvn package -Dquarkus.profile=dev
# Test run app locally
java -jar target/freelancer-1.0.0-runner.jar

# Build with Default Profile
# This will use default profile
# Check application.properties for RDMBS configuration
# You can also have you own in ./config/application.proprites 
# relative path to where your jar is reside.
mvn package -DskipTests=true

# Build Uber JAR. if you want just on jar file
# By default, Quarkus will separate lib in directory lib/
mvn package -Dquarkus.package.uber-jar=true

# Build Native Binary with Dev Profile
# (Add dev profile if you want)
mvn package -Pnative

# Build Native Binary for Container
# (Add dev profile if you want)
mvn cpackage -Dquarkus.native.container-build=true -Pnative
----

== Build Container

There are 2 Dockerfile provided:

Remark: Check that link:.dockerignore[.dockerignore] is included runner,jar and lib in folder target

* Build container with JAR by Dockerfile ( link:src/main/docker/Dockerfile.jvm[Dockerfile.jvm] )
    
[source,bash]
----
mvn package -DskipTests=true
docker build -f src/main/docker/Dockerfile.jvm \
-t ${CONTAINER_NAME}:${TAG} .
----

* Build container with Native Binary by Dockerfile ( link:src/main/docker/Dockerfile.native[Dockerfile.native] )

[source,bash]
----
mvn package -DskipTests=true -Dquarkus.native.container-build=true -Pnative
docker build -f src/main/docker/Dockerfile.native \
-t ${CONTAINER_NAME}:${TAG} .
----

== Deploy on OpenShfit 

Deploy PostgreSQL with initial data

[source,bash]
----
cd etc
./create_postgresql.sh
----

=== Build Java Application

* Build JAR with maven

[source,bash]
----
mvn clean package -DskipTests=true
----

* Create build config with binary mode

[source,bash]
----
APP_NAME=freelancer
oc new-build --binary --name=${APP_NAME} -l app=${APP_NAME}

# Sample output
* A Docker build using binary input will be created
* The resulting image will be pushed to image stream tag "freelancer:latest"
* A binary build was created, use 'oc start-build --from-dir' to trigger a new build

--> Creating resources with label app=freelancer ...
    imagestream.image.openshift.io "freelancer" created
    buildconfig.build.openshift.io "freelancer" created
--> Success
----

* Patch build configuration with :link:src/main/docker/Doeckerfile.jvm[Dockerfile.jvm]

[source,bash]
----
oc patch bc/${APP_NAME} \
-p "{\"spec\":{\"strategy\":{\"dockerStrategy\":{\"dockerfilePath\":\"src/main/docker/Dockerfile.jvm\"}}}}"

# Sample output
buildconfig.build.openshift.io/freelancer patched
----

* Start Build

[source,bash]
----
oc start-build ${APP_NAME} --from-dir=. --follow

# Sample output
....
Uploading finished
build.build.openshift.io/freelancer-1 started
Receiving source from STDIN as archive ...
Caching blobs under "/var/cache/blobs".

Pulling image registry.access.redhat.com/ubi8/ubi-minimal:8.1 ..
... 
...
Storing signatures
Successfully pushed image-registry.openshift-image-registry.svc:5000/sample/freelancer@sha256:3a2a636ace331ee7f2d5fd0d123d2f53e12bbd7134525e8fb8572e3af49823dc
Push successful
----

* Create your freelancer application then pause rollout (to configure deployment first)

[source,bash]
----
oc new-app --image-stream=${APP_NAME}:latest
oc rollout pause dc ${APP_NAME}
----

* Set probe for liveness and readiness

[source,bash]
----
oc set probe dc/${APP_NAME} --readiness --get-url=http://:8080/health/ready --initial-delay-seconds=15 --failure-threshold=1 --period-seconds=10
oc set probe dc/${APP_NAME} --liveness --get-url=http://:8080/health/live --initial-delay-seconds=10 --failure-threshold=3 --period-seconds=10
----

* Create config map and mount configmap into pods at path /deployments/config/application.properties (This will overwrite application.properties packaged into JAR)

[source,bash]
----
oc delete configmap ${APP_NAME}
oc create configmap ${APP_NAME} --from-file=config/application.properties
oc set volume dc/${APP_NAME} --add --name=${APP_NAME}-config \
--mount-path=/deployments/config/application.properties \
--sub-path=application.properties \
--configmap-name=${APP_NAME}
----

* Resume application deployment

[source,bash]
----
oc rollout resume dc ${APP_NAME}
# check that freelancer pod is running
oc get pods -l deploymentconfig=freelancer
NAME                 READY   STATUS    RESTARTS   AGE
freelancer-2-c72bs   1/1     Running   0          78s
----

* Expose service freelancer

[source,bash]
----
# Expose Service
oc expose svc/${APP_NAME}
# or create Route with TLS
oc create route edge ${APP_NAME} --service=${APP_NAME} --port=8080
----

* Test Freelancer App

[source,bash]
----
# Get Route URL
URL=$(oc get route ${APP_NAME} -o jsonpath='{.spec.host}')

# Get All freelancers
curl https://${URL}/freelancers

# Add new freelancer
curl -v -X POST -H "Content-Type: application/json" -d @etc/999999.json  https://${URL}/freelancers

# Verify that new freelancer is added
curl https://${URL}/freelancers/999999

# Delete freelancer 999999
curl -v -X DELETE https://${URL}/freelancers/999999

# Liveness & Readiness
curl https://${URL}/health/live
curl https://${URL}/health/ready

# Metrics Data
curl https://${URL}/metrics
curl https://${URL}/metrics/application
curl -H "Accept: application/json"  https://${URL}/metrics/application
----

=== Build Native Container
WIP
// === Source-to-Image (S2I) with Java Application

// * Quarkus support S2I that you can build with "oc new-app". You also need S2I configuration file at link:.s2i/environment[.s2i/environment]

// [source,bash]
// ----
// ARTIFACT_COPY_ARGS=-p -r lib/ *-runner.jar
// JAVA_OPTIONS=-Dquarkus.http.host=0.0.0.0
// ----

// * Start build and deploy to OpenShift with "oc new-app"

// [source,bash]
// ----
// # Git URL
// APP_GIT_REPOSITORY=https://gitlab.com/ocp-demo/freelancer-quarkus.git
// BASE_IMAGE=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
// APP_NAME=freelancer
// # Build & Deploy
// oc new-app \
// ${BASE_IMAGE}~${APP_GIT_REPOSITORY} \
// --name=${APP_NAME}
// # Check for result
// ----

// * Check for build log

// [source,bash]
// ----
// oc logs -f bc/${APP_NAME}
// ----

// * Check for freelancer pod

// [source,bash]
// ----
// oc get pods -l app=freelancer

// ----

// * Expose service freelancer

// [source,bash]
// ----
// # Expose Service
// oc expose svc/${APP_NAME}
// # or create Route with TLS
// oc create route edge ${APP_NAME} --service=${APP_NAME} --port=8080
// ----

// * Test Freelancer App

// [source,bash]
// ----
// # Get URL
// URL=$(oc get route ${APP_NAME} -o jsonpath='{.spec.host}')

// ----